version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "bingw"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
