import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const pilot='D:/database/mentors/ying wang pilot';
const ok=(v,m)=>{if(!v)throw new Error(m)};
const read=(p)=>fs.readFileSync(p,'utf8');
const hash=(p)=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex').toUpperCase();
const cards=read(path.join(root,'ying_pilot_r1_r2_knowledge_cards_v0.3.jsonl')).trim().split(/\r?\n/).map(JSON.parse);
ok(cards.length===92,'card total');
ok(new Set(cards.map(c=>c.cardId)).size===92,'unique ids');
ok(cards.every(c=>Object.keys(c).length===20),'20-field schema');
ok(cards.every(c=>c.mentorId==='ying-pilot'),'mentor id');
ok(cards.filter(c=>c.cardId.startsWith('YWP-R1-')).length===65,'R1 count');
const r2=cards.filter(c=>c.cardId.startsWith('YWP-R2-'));
ok(r2.length===27,'R2 count');
ok(r2.every((c,i)=>c.cardId===`YWP-R2-${String(i+1).padStart(3,'0')}`),'R2 continuity');
ok(cards.filter(c=>c.knowledgeClass==='external_approved').length===89,'external count');
ok(cards.filter(c=>c.knowledgeClass==='internal_approved').length===3,'internal count');
ok(cards.filter(c=>c.knowledgeClass.endsWith('_pending')).length===0,'pending zero');
ok(cards.filter(c=>c.disclosureMode==='exact').length===7,'exact count');
ok(cards.filter(c=>c.disclosureMode==='generalized').length===82,'generalized count');
ok(cards.filter(c=>c.disclosureMode==='none').length===3,'none count');
ok(cards.filter(c=>c.caseText!==null).length===0,'formal case zero');
ok(cards.filter(c=>c.knowledgeClass==='internal_approved').every(c=>c.disclosureMode==='none'),'internal disclosure');
ok(cards.every(c=>!c.cardId.startsWith('YIN-')),'no formal ids');
const prompt=path.join(root,'Ying_Wang_Pilot_分身SystemPrompt_candidate_v0.4.md');
const persona=path.join(root,'prompt-system/mentors/ying-pilot/persona.md');
ok(hash(prompt)===hash(persona),'prompt/persona identity');
const mf=JSON.parse(read(path.join(root,'prompt-system/mentors/ying-pilot/manifest.json')));
ok(mf.id==='ying-pilot'&&mf.version==='0.4.0'&&mf.status==='draft','prompt manifest');
ok(mf.knowledgeNamespace==='mentor:ying-pilot','namespace');
const profile=JSON.parse(read(path.join(root,'ying_pilot_public_profile_v0.1.json')));
ok(profile.mentorId==='ying-pilot'&&profile.testOnly===true&&profile.publicationAuthorized===false,'test profile');
const sm=JSON.parse(read(path.join(root,'source_manifest_final.json')));
ok(sm.sources.length===8,'source count');
for(const s of sm.sources){const p=path.join(pilot,s.relativePath);ok(fs.statSync(p).size===s.bytes,`bytes ${s.sourceId}`);ok(hash(p)===s.sha256,`hash ${s.sourceId}`)}
const review=path.join(pilot,'Ying_Wang_第二轮审核清单_v0.2_回复.md');
ok(hash(review)===hash(path.join(root,'review-source/Ying_Wang_Pilot_第二轮审核清单_v0.2_回复.md')),'review snapshot');
const rootDirs=fs.readdirSync(pilot,{withFileTypes:true}).filter(x=>x.isDirectory()).map(x=>x.name).sort();
ok(JSON.stringify(rootDirs)===JSON.stringify(['work','ying wang pilot audio','ying wang pilot word'].sort()),'pilot root directories');
const handoff=read(path.join(root,'TRAE_HANDOFF.md'));
ok(handoff.includes('knowledgeClass=external_approved')&&handoff.includes('不得自动修改'), 'handoff gates');
const files=[];const walk=d=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);e.isDirectory()?walk(p):files.push(p)}};walk(root);
ok(files.length===27,'core file count');
console.log('PASS ying-pilot-final-handoff-v0.4');
console.log(JSON.stringify({files:files.length,cards:cards.length,r1:65,r2:27,externalApproved:89,internalApproved:3,pending:0,formalCases:0,sources:8,audioDurationSec:sm.audioTotalDurationSec,manifest:mf.status},null,2));
